services:
  channelfinder:
    build: .
    image: channelfinder
    hostname: channelfinder
    networks:
      - channelfinder-net
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ELASTICSEARCH_NETWORK_HOST=elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    hostname: elasticsearch
    networks:
      - channelfinder-net
    ports:
      - "9200:9200"
    environment:
      cluster.name: channelfinder
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      EPICS_PVAS_INTF_ADDR_LIST: "0.0.0.0"
    volumes:
      - channelfinder-es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  channelfinder-es-data:
    driver: local

networks:
  channelfinder-net:
    driver: bridge
