version: "3"
services:
  channelfinder:
    build: .
    image: channelfinder
    hostname: channelfinder
    networks:
      - channelfinder-net
    ports:
      - "8443:8443"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_NETWORK_HOST=elasticsearch-cf
    command: >
      /bin/bash -c "
        until curl --silent --fail http://elasticsearch-cf:9200/_cluster/health; do
          echo 'Waiting for Elasticsearch'
          sleep 1
        done
        java -jar /channelfinder/ChannelFinder-4.7.0.jar"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    hostname: elasticsearch-cf
    networks:
      - channelfinder-net
    ports:
      - "9200:9200"
    environment:
      cluster.name: channelfinder
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
    volumes:
      - channelfinder-es-data:/usr/share/elasticsearch/data

volumes:
  channelfinder-es-data:
    driver: local

networks:
  channelfinder-net:
    driver: bridge
