# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Code coverage

on:
  push:
    branches: [ "master" ]

jobs:
  codecov:
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: ankane/setup-elasticsearch@v1
      with:
        elasticsearch-version: 8
        config: |
          http.port: 9200
    - name: Clear existing docker image cache
      shell: bash
      run: docker image prune -af
    - name: Integration Test with Maven
      run: mvn clean install test-compile failsafe:integration-test failsafe:verify jacoco:report --batch-mode --fail-at-end
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/target/failsafe-reports/TEST-*.xml'
    - name: Publish test coverage results
      uses: PavanMudigonda/jacoco-reporter@v4.8
      with:
        coverage_results_path: 'target/site/jacoco/jacoco.xml'
        coverage_report_title: 'Test coverage results'
        coverage_report_name: 'Test coverage results'
    - name: Upload Code Coverage Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report-markdown
        path: '*/coverage-results.md'
